---
title: '機械学習のための、ゼロからはじめる統計のお話'
author: '石井 遼介 / @ryouen'
date: "March 8, 2019"
output:
  bookdown::gitbook: default
  html_document:  
    latex_engine: xelatex
    df_print: paged
    toc: true
    toc_float: true
    toc_depth: '2'
  pdf_document:
#    latex_engine: xelatex
    df_print: kable
    number_sections: yes
    toc: no
    toc_depth: 
output_file: "index.html"
fontsize: 11pt
#bibliography: mybibfile.bib
mainfont: Meiryo
monofont: Meiryo
---


```{r include=FALSE}
#install.packages("bookdown")
#install.packages("rmarkdown")
#install.packages("knitr")
#install.packages("devtools", dependencies = TRUE)
#install.packages("reticulate") #このパッケージを使うと、'''{python} チャンクでPythonを実行する時、チャンクをまたいだ処理も可能になる
#devtools::install_github("rstudio/rmarkdown")
library(bookdown)
library(rmarkdown)
library(knitr)
library(reticulate)
```

#index{-}
このページでは、機械学習をやってみたい、AI入門したい、あるいは、統計をゼロから学びたい、という方のために、
統計の基礎を、**わかりやすく、けれど、本質を損なわないように**お伝えしていきます。

筆者はRとPythonを使いますが、[こちらのGithubのリポジトリに利用するファイルをすべて置いて](https://github.com/ryouen/ryouen.github.io/tree/master/stat)おきます。

###対象読者
 - これから統計に入門するヒト。機械学習とかAIとかの入り口にたった人
 - 研究者で統計パッケージを使って分析ができるが「自分が本当には、何をしているのか？」を知りたい人
 - 統計の最新知識が、20年前学部生の時で止まっている、社会学者の方


###数式はこわくない{-}
この統計分析では「数式」を使います。
数式について、苦手意識がある方は、この章をこのまま読み進めてから、本題に入ってください。
数式に苦手意識などないよ、という方は、早速第１章から入っていきましょう。

###数式は「ラク」をするためにある{-}
統計を学ぶ上で、「数式」は避けられません。
数式というと、苦手、難しそう、なんなら「得体が知れなくて怖い！」という方もいらっしゃるかもしれません。
しかし、数式は、実は「ラクをするために」あるのです、と言ったら、驚かれるでしょうか？

例えば、もしあなたが数式が苦手なら、

\[
  \sum_{x=1}^{5} x
\]


みたいなのは、できれば見たくないですよね。


ではぎゃくに、こういうのを見るとどうでしょう？
\[
いち　たす　に　たす　さん　たす　よん　たす　ご
\]

さすがに、

\[
1+2+3+4+5
\]
と書いてよね、まどろっこしいなあ。などと、思われるのではないでしょうか。


**実は、本質的には、すべての数学の記号は、これと同じ。長い言葉を省略しているに過ぎません。**


###難しいのではなく、知らない{-}

だから、数式を見たら、一度それを「日本語へ翻訳」してみてください。
たとえば、先程みた

\[
  \sum_{x=1}^{5} x
\]
この数式は、
\[
1から5まで、順番に足していって。つまり、1+2+3+4+5をして！
\]

という「日本語へ翻訳」できます。

日本語へ翻訳できないこ時、それは
**数式が難しいのではなく、あなたがその数式を知らないだけ**なのです。
知識がない時、必要なのは落ち込むことではなく、調べることです。知ることです。

もっと言えば、**大事なことは「数式に慣れる」こと**です。
わたしたちは、本当にはよく分からなくても、見慣れているものを「わかる」と思う生き物です。

例えば、いつも使っている携帯電話は、統計で学ぶひとつひとつの数式に比べると、
高度なテクノロジーの塊で、とても難しいはずです。

けれど「なぜ、そのボタンを押すと、遠く離れたヒトと話ができるという、魔術的なことが起きるのか？？う～～ん、まったくわからん。俺は頭が悪いのだろうか。。」と落ち込むことなどなく、自然に使いこなしているはずです。

数式は、むしろ「語学」だと思って、むかし英語の単語帳を何度も見て覚えたように、
そして今では「Pen」という単語を見ると、「なんだっけ、えーと、確か、ペンだな」などと思うことなく、
「Pen」が指し示すものを、１秒のタイムラグもなく理解できるように、
統計の数式にも、時間をかけて、何度も見て、慣れていくことが大切です。

新しい英単語を、一度見てすぐに使えるようにならないのと同じように、
新しい数式に、時間をかけて慣れ親しんでいきましょう。


#線形回帰分析

回帰分析とは、


##回帰分析とは

##線形回帰

#重回帰分析

回帰分析について学んでいきましょう！！

#統計デモ


#参考文献

 - STAT-GB/2301 by Jeffrey S. Simonoff in New York University
 

